[tool.poetry]
name = "tic-tac-toe"
version = "0.1.0"
packages = [{ include = "tictactoe", from="src" }]

[tool.poetry.dependencies]
python = ">=3.12"
RLTools = {path = "../../..", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"